version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/eeekgamesbot/eeekgamesbot
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: admin
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: admin
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: admin 
